//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRN()
        {
            this.SubGRN = new HashSet<SubGRN>();
        }
    
        public int GRNId { get; set; }
        public string AccountYear { get; set; }
        public int IncrementId { get; set; }
        public string GRNNO { get; set; }
        public System.DateTime GRNDate { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> GateInwardDate { get; set; }
        public int SupplierId { get; set; }
        public string RequestBy { get; set; }
        public string GRNType { get; set; }
        public decimal SubTotal { get; set; }
        public decimal CGST { get; set; }
        public decimal SGST { get; set; }
        public decimal IGST { get; set; }
        public decimal Total { get; set; }
        public int IsActive { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createdon { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public string SuppInvoiceNo { get; set; }
        public Nullable<System.DateTime> SuppInvoiceDate { get; set; }
        public string SuppInvoiceFile { get; set; }
        public Nullable<decimal> CourierCharges { get; set; }
        public Nullable<int> POId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubGRN> SubGRN { get; set; }
    }
}
