//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.SubInvoice = new HashSet<SubInvoice>();
        }
    
        public int InvoiceId { get; set; }
        public string AccountYear { get; set; }
        public int IncrementId { get; set; }
        public string InvoiceNO { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Location { get; set; }
        public string Taxable { get; set; }
        public string DCNo { get; set; }
        public Nullable<System.DateTime> DCDate { get; set; }
        public int CustomerId { get; set; }
        public string Currency { get; set; }
        public decimal ExchangeRate { get; set; }
        public string PlaceOfSupply { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string PaymentType { get; set; }
        public string Transport { get; set; }
        public string PreparedBy { get; set; }
        public string Remarks { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public decimal SubTotal { get; set; }
        public decimal CGST { get; set; }
        public decimal SGST { get; set; }
        public decimal IGST { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<decimal> CourierCharges { get; set; }
        public decimal Total { get; set; }
        public int IsActive { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createdon { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public string DeliveryType { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubInvoice> SubInvoice { get; set; }
    }
}
