//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningStock
    {
        public int OpeningStockId { get; set; }
        public string AccountYear { get; set; }
        public int IncrementId { get; set; }
        public string OpeningStockNo { get; set; }
        public int ItemId { get; set; }
        public decimal ActualStock { get; set; }
        public decimal PhysicalStock { get; set; }
        public string PreparedBy { get; set; }
        public string Remarks { get; set; }
        public int IsActive { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Createdon { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
