// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly CandidatesClass s_Candidates = new CandidatesClass();
    public static CandidatesClass Candidates { get { return s_Candidates; } }
    static readonly ConfigurationClass s_Configuration = new ConfigurationClass();
    public static ConfigurationClass Configuration { get { return s_Configuration; } }
    static readonly EmployeeClass s_Employee = new EmployeeClass();
    public static EmployeeClass Employee { get { return s_Employee; } }
    public static HRMS.UI.Controllers.ErrorController Error = new HRMS.UI.Controllers.T4MVC_ErrorController();
    public static HRMS.UI.Controllers.HomeController Home = new HRMS.UI.Controllers.T4MVC_HomeController();
    public static HRMS.UI.Controllers.HRMS_CommonController HRMS_Common = new HRMS.UI.Controllers.T4MVC_HRMS_CommonController();
    public static HRMS.UI.Controllers.ReportsController Reports = new HRMS.UI.Controllers.T4MVC_ReportsController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class CandidatesClass
    {
        public readonly string Name = "Candidates";
        public HRMS.UI.Areas.Candidates.Controllers.CandidatesController Candidates = new HRMS.UI.Areas.Candidates.Controllers.T4MVC_CandidatesController();
        public T4MVC.Candidates.SharedController Shared = new T4MVC.Candidates.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class ConfigurationClass
    {
        public readonly string Name = "Configuration";
        public HRMS.UI.Areas.Configuration.Controllers.ConfigurationController Configuration = new HRMS.UI.Areas.Configuration.Controllers.T4MVC_ConfigurationController();
        public T4MVC.Configuration.SharedController Shared = new T4MVC.Configuration.SharedController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class EmployeeClass
    {
        public readonly string Name = "Employee";
        public HRMS.UI.Areas.Employee.Controllers.EmployeeInformationController EmployeeInformation = new HRMS.UI.Areas.Employee.Controllers.T4MVC_EmployeeInformationController();
        public HRMS.UI.Areas.Employee.Controllers.JoinedEmployeeController JoinedEmployee = new HRMS.UI.Areas.Employee.Controllers.T4MVC_JoinedEmployeeController();
        public HRMS.UI.Areas.Employee.Controllers.PersonalInformationController PersonalInformation = new HRMS.UI.Areas.Employee.Controllers.T4MVC_PersonalInformationController();
        public T4MVC.Employee.EmployeeController Employee = new T4MVC.Employee.EmployeeController();
        public T4MVC.Employee.SharedController Shared = new T4MVC.Employee.SharedController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class BirthdayCard {
            private const string URLPATH = "~/Scripts/BirthdayCard";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                private const string URLPATH = "~/Scripts/BirthdayCard/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class js {
                private const string URLPATH = "~/Scripts/BirthdayCard/js";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string index_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/index.min.js") ? Url("index.min.js") : Url("index.js");
            }
        
        }
    
        public static readonly string bootstrap_dialog_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-dialog.min.js") ? Url("bootstrap-dialog.min.js") : Url("bootstrap-dialog.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Common {
            private const string URLPATH = "~/Scripts/Common";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string Application_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Application.min.js") ? Url("Application.min.js") : Url("Application.js");
        }
    
        public static readonly string common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/common.min.js") ? Url("common.min.js") : Url("common.js");
        public static readonly string cookies_min_js = Url("cookies.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class DataTableExport {
            private const string URLPATH = "~/Scripts/DataTableExport";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string buttons_flash_min_js = Url("buttons.flash.min.js");
            public static readonly string buttons_html5_min_js = Url("buttons.html5.min.js");
            public static readonly string buttons_print_min_js = Url("buttons.print.min.js");
            public static readonly string dataTables_buttons_min_js = Url("dataTables.buttons.min.js");
            public static readonly string jszip_min_js = Url("jszip.min.js");
            public static readonly string pdfmake_min_js = Url("pdfmake.min.js");
            public static readonly string vfs_fonts_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/vfs_fonts.min.js") ? Url("vfs_fonts.min.js") : Url("vfs_fonts.js");
        }
    
        public static readonly string dataTables_bootstrap4_min_js = Url("dataTables.bootstrap4.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class DateFormat {
            private const string URLPATH = "~/Scripts/DateFormat";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string Dateformat_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Dateformat.min.js") ? Url("Dateformat.min.js") : Url("Dateformat.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class HRMS {
            private const string URLPATH = "~/Scripts/HRMS";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string HRMS_Common_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/HRMS_Common.min.js") ? Url("HRMS_Common.min.js") : Url("HRMS_Common.js");
            public static readonly string OfferedCandidate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/OfferedCandidate.min.js") ? Url("OfferedCandidate.min.js") : Url("OfferedCandidate.js");
            public static readonly string PreviewCandidateForm_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/PreviewCandidateForm.min.js") ? Url("PreviewCandidateForm.min.js") : Url("PreviewCandidateForm.js");
        }
    
        public static readonly string html5shiv_printshiv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/html5shiv-printshiv.min.js") ? Url("html5shiv-printshiv.min.js") : Url("html5shiv-printshiv.js");
        public static readonly string html5shiv_printshiv_min_js = Url("html5shiv-printshiv.min.js");
        public static readonly string html5shiv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/html5shiv.min.js") ? Url("html5shiv.min.js") : Url("html5shiv.js");
        public static readonly string html5shiv_min_js = Url("html5shiv.min.js");
        public static readonly string jquery_1_12_4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.12.4.min.js") ? Url("jquery-1.12.4.min.js") : Url("jquery-1.12.4.js");
        public static readonly string jquery_3_1_0_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-3.1.0.intellisense.min.js") ? Url("jquery-3.1.0.intellisense.min.js") : Url("jquery-3.1.0.intellisense.js");
        public static readonly string jquery_3_1_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-3.1.0.min.js") ? Url("jquery-3.1.0.min.js") : Url("jquery-3.1.0.js");
        public static readonly string jquery_3_1_0_min_js = Url("jquery-3.1.0.min.js");
        public static readonly string jquery_3_1_0_min_map = Url("jquery-3.1.0.min.map");
        public static readonly string jquery_3_1_0_slim_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-3.1.0.slim.min.js") ? Url("jquery-3.1.0.slim.min.js") : Url("jquery-3.1.0.slim.js");
        public static readonly string jquery_3_1_0_slim_min_js = Url("jquery-3.1.0.slim.min.js");
        public static readonly string jquery_3_1_0_slim_min_map = Url("jquery-3.1.0.slim.min.map");
        public static readonly string jquery_deparam_min_js = Url("jquery-deparam.min.js");
        public static readonly string jquery_ui_1_12_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.12.0.min.js") ? Url("jquery-ui-1.12.0.min.js") : Url("jquery-ui-1.12.0.js");
        public static readonly string jquery_ui_1_12_0_min_js = Url("jquery-ui-1.12.0.min.js");
        public static readonly string jquery_ui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.js") ? Url("jquery-ui.min.js") : Url("jquery-ui.js");
        public static readonly string jquery_bxslider_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.bxslider.min.js") ? Url("jquery.bxslider.min.js") : Url("jquery.bxslider.js");
        public static readonly string jquery_bxslider_min_js = Url("jquery.bxslider.min.js");
        public static readonly string jquery_dataTables_min_js = Url("jquery.dataTables.min.js");
        public static readonly string jquery_easing_1_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.easing.1.3.min.js") ? Url("jquery.easing.1.3.min.js") : Url("jquery.easing.1.3.js");
        public static readonly string jquery_fitvids_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.fitvids.min.js") ? Url("jquery.fitvids.min.js") : Url("jquery.fitvids.js");
        public static readonly string jquery_metadata_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.metadata.min.js") ? Url("jquery.metadata.min.js") : Url("jquery.metadata.js");
        public static readonly string jquery_redirect_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.redirect.min.js") ? Url("jquery.redirect.min.js") : Url("jquery.redirect.js");
        public static readonly string jquery_tablesorter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.tablesorter.min.js") ? Url("jquery.tablesorter.min.js") : Url("jquery.tablesorter.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_vsdoc_js_ = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_date_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.date.min.js") ? Url("jquery.validate.date.min.js") : Url("jquery.validate.date.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class JQueryMask {
            private const string URLPATH = "~/Scripts/JQueryMask";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string jquery_mask_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mask.min.js") ? Url("jquery.mask.min.js") : Url("jquery.mask.js");
            public static readonly string jquery_mask_min_js = Url("jquery.mask.min.js");
        }
    
        public static readonly string jssor_slider_min_js = Url("jssor.slider.min.js");
        public static readonly string jssor_slider_mini_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jssor.slider.mini.min.js") ? Url("jssor.slider.mini.min.js") : Url("jssor.slider.mini.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jsTree3 {
            private const string URLPATH = "~/Scripts/jsTree3";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string jstree_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jstree.min.js") ? Url("jstree.min.js") : Url("jstree.js");
            public static readonly string jstree_min_js = Url("jstree.min.js");
            public static readonly string jstreegrid_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jstreegrid.min.js") ? Url("jstreegrid.min.js") : Url("jstreegrid.js");
            public static readonly string jstreegrid_min_js = Url("jstreegrid.min.js");
        }
    
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string placeholder_IE_fixes_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/placeholder-IE-fixes.min.js") ? Url("placeholder-IE-fixes.min.js") : Url("placeholder-IE-fixes.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_matchmedia_addListener_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.matchmedia.addListener.min.js") ? Url("respond.matchmedia.addListener.min.js") : Url("respond.matchmedia.addListener.js");
        public static readonly string respond_matchmedia_addListener_min_js = Url("respond.matchmedia.addListener.min.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class assets {
            private const string URLPATH = "~/Content/assets";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                private const string URLPATH = "~/Content/assets/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string app_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/app.min.css") ? Url("app.min.css") : Url("app.css");
                public static readonly string blocks_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/blocks.min.css") ? Url("blocks.min.css") : Url("blocks.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class footers {
                    private const string URLPATH = "~/Content/assets/css/footers";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string footer_v1_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/footer-v1.min.css") ? Url("footer-v1.min.css") : Url("footer-v1.css");
                }
            
                public static readonly string global_style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/global-style.min.css") ? Url("global-style.min.css") : Url("global-style.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class headers {
                    private const string URLPATH = "~/Content/assets/css/headers";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string header_default_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/header-default.min.css") ? Url("header-default.min.css") : Url("header-default.css");
                }
            
                public static readonly string ie8_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ie8.min.css") ? Url("ie8.min.css") : Url("ie8.css");
                public static readonly string menudropdown_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/menudropdown.min.css") ? Url("menudropdown.min.css") : Url("menudropdown.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class plugins {
                    private const string URLPATH = "~/Content/assets/css/plugins";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string style_switcher_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style-switcher.min.css") ? Url("style-switcher.min.css") : Url("style-switcher.css");
                }
            
                public static readonly string plugins_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/plugins.min.css") ? Url("plugins.min.css") : Url("plugins.css");
                public static readonly string print_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/print.min.css") ? Url("print.min.css") : Url("print.css");
                public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class img {
                private const string URLPATH = "~/Content/assets/img";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string banner_image2_jpg = Url("banner-image2.jpg");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class bg {
                    private const string URLPATH = "~/Content/assets/img/bg";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _11_jpg = Url("11.jpg");
                    public static readonly string _14_jpg = Url("14.jpg");
                    public static readonly string _16_jpg = Url("16.jpg");
                    public static readonly string _18_jpg = Url("18.jpg");
                    public static readonly string _19_jpg = Url("19.jpg");
                    public static readonly string _25_jpg = Url("25.jpg");
                    public static readonly string _7_jpg = Url("7.jpg");
                }
            
                public static readonly string bg_shadow_png = Url("bg-shadow.png");
                public static readonly string big_idea_bg_png = Url("big-idea-bg.png");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class breadcrumbs {
                    private const string URLPATH = "~/Content/assets/img/breadcrumbs";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string img1_jpg = Url("img1.jpg");
                    public static readonly string img2_jpg = Url("img2.jpg");
                    public static readonly string img3_jpg = Url("img3.jpg");
                }
            
                public static readonly string events_1_jpg = Url("events-1.jpg");
                public static readonly string events_2_jpg = Url("events-2.jpg");
                public static readonly string events_3_jpg = Url("events-3.jpg");
                public static readonly string footer_logo_png = Url("footer-logo.png");
                public static readonly string headshot_1_jpg = Url("headshot-1.jpg");
                public static readonly string headshot_2_jpg = Url("headshot-2.jpg");
                public static readonly string headshot_3_jpg = Url("headshot-3.jpg");
                public static readonly string headshot_4_jpg = Url("headshot-4.jpg");
                public static readonly string headshot_5_jpg = Url("headshot-5.jpg");
                public static readonly string headshot_6_jpg = Url("headshot-6.jpg");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class icons {
                    private const string URLPATH = "~/Content/assets/img/icons";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class flat {
                        private const string URLPATH = "~/Content/assets/img/icons/flat";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string _01_png = Url("01.png");
                        public static readonly string _02_png = Url("02.png");
                        public static readonly string _03_png = Url("03.png");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class social {
                        private const string URLPATH = "~/Content/assets/img/icons/social";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string amazon_png = Url("amazon.png");
                        public static readonly string behance_png = Url("behance.png");
                        public static readonly string blogger_png = Url("blogger.png");
                        public static readonly string deviantart_png = Url("deviantart.png");
                        public static readonly string dribbble_png = Url("dribbble.png");
                        public static readonly string dropbox_png = Url("dropbox.png");
                        public static readonly string evernote_png = Url("evernote.png");
                        public static readonly string facebook_png = Url("facebook.png");
                        public static readonly string forrst_png = Url("forrst.png");
                        public static readonly string github_png = Url("github.png");
                        public static readonly string googleplus_png = Url("googleplus.png");
                        public static readonly string instagram_png = Url("instagram.png");
                        public static readonly string jolicloud_png = Url("jolicloud.png");
                        public static readonly string last_fm_png = Url("last-fm.png");
                        public static readonly string linkedin_png = Url("linkedin.png");
                        public static readonly string picasa_png = Url("picasa.png");
                        public static readonly string pintrest_png = Url("pintrest.png");
                        public static readonly string rss_png = Url("rss.png");
                        public static readonly string skype_png = Url("skype.png");
                        public static readonly string spotify_png = Url("spotify.png");
                        public static readonly string stumbleupon_png = Url("stumbleupon.png");
                        public static readonly string tumblr_png = Url("tumblr.png");
                        public static readonly string twitter_png = Url("twitter.png");
                        public static readonly string vimeo_png = Url("vimeo.png");
                        public static readonly string vk_png = Url("vk.png");
                        public static readonly string wordpress_png = Url("wordpress.png");
                        public static readonly string xing_png = Url("xing.png");
                        public static readonly string yahoo_png = Url("yahoo.png");
                        public static readonly string youtube_png = Url("youtube.png");
                    }
                
                    public static readonly string video_play_png = Url("video-play.png");
                }
            
                public static readonly string logo1_default_png = Url("logo1-default.png");
                public static readonly string logo2_default_png = Url("logo2-default.png");
                public static readonly string manu_bg_jpg = Url("manu-bg.jpg");
                public static readonly string map_img_png = Url("map-img.png");
                public static readonly string news_1_jpg = Url("news-1.jpg");
                public static readonly string news_2_jpg = Url("news-2.jpg");
                public static readonly string news_3_jpg = Url("news-3.jpg");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class patterns {
                    private const string URLPATH = "~/Content/assets/img/patterns";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _16_png = Url("16.png");
                    public static readonly string _17_png = Url("17.png");
                    public static readonly string _5_png = Url("5.png");
                    public static readonly string breadcrumbs_png = Url("breadcrumbs.png");
                    public static readonly string gridtile_png = Url("gridtile.png");
                }
            
                public static readonly string s_1_png = Url("s-1.png");
                public static readonly string s_2_jpg = Url("s-2.jpg");
                public static readonly string s_bg_png = Url("s-bg.png");
                public static readonly string slider_1_jpg = Url("slider-1.jpg");
                public static readonly string sp_1_jpg = Url("sp-1.jpg");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class team {
                    private const string URLPATH = "~/Content/assets/img/team";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string faces_jpg = Url("faces.jpg");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class transparent {
                    private const string URLPATH = "~/Content/assets/img/transparent";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string black_png = Url("black.png");
                    public static readonly string white_png = Url("white.png");
                }
            
                public static readonly string want_to_bg_png = Url("want-to-bg.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class plugins {
                private const string URLPATH = "~/Content/assets/plugins";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string animate_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/animate.min.css") ? Url("animate.min.css") : Url("animate.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class atomic {
                    private const string URLPATH = "~/Content/assets/plugins/atomic";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string atomic_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/atomic.min.css") ? Url("atomic.min.css") : Url("atomic.css");
                }
            
                public static readonly string back_to_top_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/back-to-top.min.js") ? Url("back-to-top.min.js") : Url("back-to-top.js");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class bootstrap {
                    private const string URLPATH = "~/Content/assets/plugins/bootstrap";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class css {
                        private const string URLPATH = "~/Content/assets/plugins/bootstrap/css";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string bootstrap_rtl_min_css = Url("bootstrap-rtl.min.css");
                        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
                        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
                        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
                        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
                        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
                        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class fonts {
                        private const string URLPATH = "~/Content/assets/plugins/bootstrap/fonts";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string glyphicons_halflings_regular_eot = Url("glyphicons-halflings-regular.eot");
                        public static readonly string glyphicons_halflings_regular_svg = Url("glyphicons-halflings-regular.svg");
                        public static readonly string glyphicons_halflings_regular_ttf = Url("glyphicons-halflings-regular.ttf");
                        public static readonly string glyphicons_halflings_regular_woff = Url("glyphicons-halflings-regular.woff");
                        public static readonly string glyphicons_halflings_regular_woff2 = Url("glyphicons-halflings-regular.woff2");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class js {
                        private const string URLPATH = "~/Content/assets/plugins/bootstrap/js";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
                        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
                        public static readonly string npm_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/npm.min.js") ? Url("npm.min.js") : Url("npm.js");
                    }
                
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Jssor {
                    private const string URLPATH = "~/Content/assets/plugins/Jssor";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string jquery_bxslider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.bxslider.min.css") ? Url("jquery.bxslider.min.css") : Url("jquery.bxslider.css");
                    public static readonly string jssor_slider_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jssor.slider.debug.min.js") ? Url("jssor.slider.debug.min.js") : Url("jssor.slider.debug.js");
                    public static readonly string MIT_LICENSE_txt = Url("MIT-LICENSE.txt");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class line_icons {
                    private const string URLPATH = "~/Content/assets/plugins/line-icons";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class fonts {
                        private const string URLPATH = "~/Content/assets/plugins/line-icons/fonts";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string Simple_Line_Icons_eot = Url("Simple-Line-Icons.eot");
                        public static readonly string Simple_Line_Icons_svg = Url("Simple-Line-Icons.svg");
                        public static readonly string Simple_Line_Icons_ttf = Url("Simple-Line-Icons.ttf");
                        public static readonly string Simple_Line_Icons_woff = Url("Simple-Line-Icons.woff");
                    }
                
                    public static readonly string line_icons_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/line-icons.min.css") ? Url("line-icons.min.css") : Url("line-icons.css");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class sky_forms_pro {
                    private const string URLPATH = "~/Content/assets/plugins/sky-forms-pro";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class skyforms {
                        private const string URLPATH = "~/Content/assets/plugins/sky-forms-pro/skyforms";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                        public static class css {
                            private const string URLPATH = "~/Content/assets/plugins/sky-forms-pro/skyforms/css";
                            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                            public static readonly string sky_forms_ie8_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sky-forms-ie8.min.css") ? Url("sky-forms-ie8.min.css") : Url("sky-forms-ie8.css");
                            public static readonly string sky_forms_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sky-forms.min.css") ? Url("sky-forms.min.css") : Url("sky-forms.css");
                        }
                    
                        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                        public static class custom {
                            private const string URLPATH = "~/Content/assets/plugins/sky-forms-pro/skyforms/custom";
                            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                            public static readonly string custom_sky_forms_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/custom-sky-forms.min.css") ? Url("custom-sky-forms.min.css") : Url("custom-sky-forms.css");
                        }
                    
                    }
                
                }
            
                public static readonly string smoothScroll_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/smoothScroll.min.js") ? Url("smoothScroll.min.js") : Url("smoothScroll.js");
            }
        
        }
    
        public static readonly string bootstrap_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-dialog.min.css") ? Url("bootstrap-dialog.min.css") : Url("bootstrap-dialog.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string buttons_dataTables_min_css = Url("buttons.dataTables.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Custom {
            private const string URLPATH = "~/Content/Custom";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string app_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/app.min.css") ? Url("app.min.css") : Url("app.css");
            public static readonly string vendor_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/vendor.min.css") ? Url("vendor.min.css") : Url("vendor.css");
        }
    
        public static readonly string dataTables_bootstrap4_min_css = Url("dataTables.bootstrap4.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Documents {
            private const string URLPATH = "~/Content/Documents";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class font_awesome {
            private const string URLPATH = "~/Content/font-awesome";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _bower_json = Url(".bower.json");
            public static readonly string _gitignore = Url(".gitignore");
            public static readonly string _npmignore = Url(".npmignore");
            public static readonly string bower_json = Url("bower.json");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                private const string URLPATH = "~/Content/font-awesome/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string font_awesome_animation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/font-awesome-animation.min.css") ? Url("font-awesome-animation.min.css") : Url("font-awesome-animation.css");
                public static readonly string font_awesome_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/font-awesome.min.css") ? Url("font-awesome.min.css") : Url("font-awesome.css");
                public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class fonts {
                private const string URLPATH = "~/Content/font-awesome/fonts";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string fontawesome_webfont_eot = Url("fontawesome-webfont.eot");
                public static readonly string fontawesome_webfont_svg = Url("fontawesome-webfont.svg");
                public static readonly string fontawesome_webfont_ttf = Url("fontawesome-webfont.ttf");
                public static readonly string fontawesome_webfont_woff = Url("fontawesome-webfont.woff");
                public static readonly string fontawesome_webfont_woff2 = Url("fontawesome-webfont.woff2");
                public static readonly string FontAwesome_otf = Url("FontAwesome.otf");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class less {
                private const string URLPATH = "~/Content/font-awesome/less";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string animated_less = Url("animated.less");
                public static readonly string bordered_pulled_less = Url("bordered-pulled.less");
                public static readonly string core_less = Url("core.less");
                public static readonly string extras_less = Url("extras.less");
                public static readonly string fixed_width_less = Url("fixed-width.less");
                public static readonly string font_awesome_less = Url("font-awesome.less");
                public static readonly string icons_less = Url("icons.less");
                public static readonly string larger_less = Url("larger.less");
                public static readonly string list_less = Url("list.less");
                public static readonly string mixins_less = Url("mixins.less");
                public static readonly string path_less = Url("path.less");
                public static readonly string rotated_flipped_less = Url("rotated-flipped.less");
                public static readonly string screen_reader_less = Url("screen-reader.less");
                public static readonly string spinning_less = Url("spinning.less");
                public static readonly string stacked_less = Url("stacked.less");
                public static readonly string variables_less = Url("variables.less");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class scss {
                private const string URLPATH = "~/Content/font-awesome/scss";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string _animated_scss = Url("_animated.scss");
                public static readonly string _bordered_pulled_scss = Url("_bordered-pulled.scss");
                public static readonly string _core_scss = Url("_core.scss");
                public static readonly string _extras_scss = Url("_extras.scss");
                public static readonly string _fixed_width_scss = Url("_fixed-width.scss");
                public static readonly string _icons_scss = Url("_icons.scss");
                public static readonly string _larger_scss = Url("_larger.scss");
                public static readonly string _list_scss = Url("_list.scss");
                public static readonly string _mixins_scss = Url("_mixins.scss");
                public static readonly string _path_scss = Url("_path.scss");
                public static readonly string _rotated_flipped_scss = Url("_rotated-flipped.scss");
                public static readonly string _screen_reader_scss = Url("_screen-reader.scss");
                public static readonly string _spinning_scss = Url("_spinning.scss");
                public static readonly string _stacked_scss = Url("_stacked.scss");
                public static readonly string _variables_scss = Url("_variables.scss");
                public static readonly string font_awesome_scss = Url("font-awesome.scss");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Fonts {
            private const string URLPATH = "~/Content/Fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string ionicons_ttf = Url("ionicons.ttf");
            public static readonly string ionicons_woff = Url("ionicons.woff");
        }
    
        public static readonly string fonts_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fonts.min.css") ? Url("fonts.min.css") : Url("fonts.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class HelpFiles {
            private const string URLPATH = "~/Content/HelpFiles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _01_jpg = Url("01.jpg");
            public static readonly string _02_jpg = Url("02.jpg");
            public static readonly string _03_jpg = Url("03.jpg");
            public static readonly string _04_jpg = Url("04.jpg");
            public static readonly string a22_png = Url("a22.png");
            public static readonly string archive_png = Url("archive.png");
            public static readonly string b05_png = Url("b05.png");
            public static readonly string batch_img_png = Url("batch-img.png");
            public static readonly string big_focused_jpg = Url("big-focused.jpg");
            public static readonly string big_future_jpg = Url("big-future.jpg");
            public static readonly string big_training_jpg = Url("big-training.jpg");
            public static readonly string big_turtle_jpg = Url("big-turtle.jpg");
            public static readonly string breadcrumbs_png = Url("breadcrumbs.png");
            public static readonly string bx_loader_gif = Url("bx_loader.gif");
            public static readonly string Calendar_png = Url("Calendar.png");
            public static readonly string controls_png = Url("controls.png");
            public static readonly string create_img_png = Url("create-img.png");
            public static readonly string down_png = Url("down.png");
            public static readonly string eval_png = Url("eval.png");
            public static readonly string falcon_jpg = Url("falcon.jpg");
            public static readonly string flower_jpg = Url("flower.jpg");
            public static readonly string footer_logo_png = Url("footer-logo.png");
            public static readonly string icon_chrome_png = Url("icon_chrome.png");
            public static readonly string icon_firefox_png = Url("icon_firefox.png");
            public static readonly string icon_ie_png = Url("icon_ie.png");
            public static readonly string icon_opera_png = Url("icon_opera.png");
            public static readonly string icon_safari_png = Url("icon_safari.png");
            public static readonly string loading_gif = Url("loading.gif");
            public static readonly string search_img_png = Url("search-img.png");
            public static readonly string SecuritySiliconHelicopter_jpg = Url("SecuritySiliconHelicopter.jpg");
            public static readonly string small_focused_jpg = Url("small-focused.jpg");
            public static readonly string small_future_jpg = Url("small-future.jpg");
            public static readonly string small_training_jpg = Url("small-training.jpg");
            public static readonly string small_turtle_jpg = Url("small-turtle.jpg");
            public static readonly string up_png = Url("up.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Imports {
            private const string URLPATH = "~/Content/Imports";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Proposals {
                private const string URLPATH = "~/Content/Imports/Proposals";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
        }
    
        public static readonly string jqGrid_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqGrid.bootstrap.min.css") ? Url("jqGrid.bootstrap.min.css") : Url("jqGrid.bootstrap.css");
        public static readonly string jquery_dataTables_min_css = Url("jquery.dataTables.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class jsTree {
            private const string URLPATH = "~/Content/jsTree";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string docs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/docs.min.css") ? Url("docs.min.css") : Url("docs.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class images {
                private const string URLPATH = "~/Content/jsTree/images";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Loading_gif = Url("Loading.gif");
                public static readonly string tree_png = Url("tree.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class themes {
                private const string URLPATH = "~/Content/jsTree/themes";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class bootstrap_theme {
                    private const string URLPATH = "~/Content/jsTree/themes/bootstrap-theme";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _32px_png = Url("32px.png");
                    public static readonly string _40px_png = Url("40px.png");
                    public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
                    public static readonly string style_min_css = Url("style.min.css");
                    public static readonly string throbber_gif = Url("throbber.gif");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class @default {
                    private const string URLPATH = "~/Content/jsTree/themes/default";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _32px_png = Url("32px.png");
                    public static readonly string _32px_Arrows_png = Url("32px_Arrows.png");
                    public static readonly string _40px_png = Url("40px.png");
                    public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
                    public static readonly string style_min_css = Url("style.min.css");
                    public static readonly string throbber_gif = Url("throbber.gif");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class default_dark {
                    private const string URLPATH = "~/Content/jsTree/themes/default-dark";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _32px_png = Url("32px.png");
                    public static readonly string _40px_png = Url("40px.png");
                    public static readonly string style_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/style.min.css") ? Url("style.min.css") : Url("style.css");
                    public static readonly string style_min_css = Url("style.min.css");
                    public static readonly string throbber_gif = Url("throbber.gif");
                }
            
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Logos {
            private const string URLPATH = "~/Content/Logos";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string Test_png = Url("Test.png");
        }
    
        public static readonly string PagedList_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/PagedList.min.css") ? Url("PagedList.min.css") : Url("PagedList.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class pdfs {
            private const string URLPATH = "~/Content/pdfs";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _FOUO__USA002725_11_Revised_Topic_Review_Criteria_Guidance_pdf = Url("(FOUO)_USA002725-11_Revised_Topic_Review_Criteria_Guidance.pdf");
            public static readonly string AF_SBIR_STTR_Topic_Generation_Guidelines_pdf = Url("AF SBIR STTR Topic Generation Guidelines.pdf");
        }
    
        public static readonly string reports_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/reports.min.css") ? Url("reports.min.css") : Url("reports.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string pencil_png = Url("pencil.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_75_ffffff_1x400_png = Url("ui-bg_glass_75_ffffff_1x400.png");
                    public static readonly string ui_bg_inset_soft_95_fef1ec_1x100_png = Url("ui-bg_inset-soft_95_fef1ec_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_444444_256x240_png = Url("ui-icons_444444_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_555555_256x240_png = Url("ui-icons_555555_256x240.png");
                    public static readonly string ui_icons_777620_256x240_png = Url("ui-icons_777620_256x240.png");
                    public static readonly string ui_icons_777777_256x240_png = Url("ui-icons_777777_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cc0000_256x240_png = Url("ui-icons_cc0000_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    public static readonly string ui_icons_f6cf3b_256x240_png = Url("ui-icons_f6cf3b_256x240.png");
                    public static readonly string ui_icons_ffffff_256x240_png = Url("ui-icons_ffffff_256x240.png");
                }
            
                public static readonly string jquery_ui_1_10_0_custom_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.10.0.custom.min.css") ? Url("jquery-ui-1.10.0.custom.min.css") : Url("jquery-ui-1.10.0.custom.css");
                public static readonly string jquery_ui_1_9_2_custom_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.9.2.custom.min.css") ? Url("jquery-ui-1.9.2.custom.min.css") : Url("jquery-ui-1.9.2.custom.css");
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                public static readonly string jquery_ui_1_10_0_ie_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.1.10.0.ie.min.css") ? Url("jquery.ui.1.10.0.ie.min.css") : Url("jquery.ui.1.10.0.ie.css");
                public static readonly string jquery_ui_1_9_2_ie_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.1.9.2.ie.min.css") ? Url("jquery.ui.1.9.2.ie.min.css") : Url("jquery.ui.1.9.2.ie.css");
                public static readonly string selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectable.min.css") ? Url("selectable.min.css") : Url("selectable.css");
                public static readonly string selectmenu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectmenu.min.css") ? Url("selectmenu.min.css") : Url("selectmenu.css");
                public static readonly string slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/slider.min.css") ? Url("slider.min.css") : Url("slider.css");
                public static readonly string sortable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sortable.min.css") ? Url("sortable.min.css") : Url("sortable.css");
                public static readonly string spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/spinner.min.css") ? Url("spinner.min.css") : Url("spinner.css");
                public static readonly string tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tabs.min.css") ? Url("tabs.min.css") : Url("tabs.css");
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                public static readonly string tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tooltip.min.css") ? Url("tooltip.min.css") : Url("tooltip.css");
            }
        
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class BirthdayCard 
            {
                public static partial class css 
                {
                    public static class Assets
                    {
                        public const string style_css = "~/Scripts/BirthdayCard/css/style.css";
                    }
                }
                public static partial class js 
                {
                    public static class Assets
                    {
                        public const string index_js = "~/Scripts/BirthdayCard/js/index.js"; 
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class Common 
            {
                public static class Assets
                {
                    public const string Application_js = "~/Scripts/Common/Application.js"; 
                }
            }
            public static partial class DataTableExport 
            {
                public static class Assets
                {
                    public const string buttons_flash_min_js = "~/Scripts/DataTableExport/buttons.flash.min.js"; 
                    public const string buttons_html5_min_js = "~/Scripts/DataTableExport/buttons.html5.min.js"; 
                    public const string buttons_print_min_js = "~/Scripts/DataTableExport/buttons.print.min.js"; 
                    public const string dataTables_buttons_min_js = "~/Scripts/DataTableExport/dataTables.buttons.min.js"; 
                    public const string jszip_min_js = "~/Scripts/DataTableExport/jszip.min.js"; 
                    public const string pdfmake_min_js = "~/Scripts/DataTableExport/pdfmake.min.js"; 
                    public const string vfs_fonts_js = "~/Scripts/DataTableExport/vfs_fonts.js"; 
                }
            }
            public static partial class DateFormat 
            {
                public static class Assets
                {
                    public const string Dateformat_js = "~/Scripts/DateFormat/Dateformat.js"; 
                }
            }
            public static partial class HRMS 
            {
                public static class Assets
                {
                    public const string HRMS_Common_js = "~/Scripts/HRMS/HRMS_Common.js"; 
                    public const string OfferedCandidate_js = "~/Scripts/HRMS/OfferedCandidate.js"; 
                    public const string PreviewCandidateForm_js = "~/Scripts/HRMS/PreviewCandidateForm.js"; 
                }
            }
            public static partial class JQueryMask 
            {
                public static class Assets
                {
                    public const string jquery_mask_js = "~/Scripts/JQueryMask/jquery.mask.js"; 
                    public const string jquery_mask_min_js = "~/Scripts/JQueryMask/jquery.mask.min.js"; 
                }
            }
            public static partial class jsTree3 
            {
                public static class Assets
                {
                    public const string jstree_js = "~/Scripts/jsTree3/jstree.js"; 
                    public const string jstree_min_js = "~/Scripts/jsTree3/jstree.min.js"; 
                    public const string jstreegrid_js = "~/Scripts/jsTree3/jstreegrid.js"; 
                    public const string jstreegrid_min_js = "~/Scripts/jsTree3/jstreegrid.min.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_dialog_js = "~/Scripts/bootstrap-dialog.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string common_js = "~/Scripts/common.js"; 
                public const string cookies_min_js = "~/Scripts/cookies.min.js"; 
                public const string dataTables_bootstrap4_min_js = "~/Scripts/dataTables.bootstrap4.min.js"; 
                public const string html5shiv_printshiv_js = "~/Scripts/html5shiv-printshiv.js"; 
                public const string html5shiv_printshiv_min_js = "~/Scripts/html5shiv-printshiv.min.js"; 
                public const string html5shiv_js = "~/Scripts/html5shiv.js"; 
                public const string html5shiv_min_js = "~/Scripts/html5shiv.min.js"; 
                public const string jquery_1_12_4_js = "~/Scripts/jquery-1.12.4.js"; 
                public const string jquery_3_1_0_intellisense_js = "~/Scripts/jquery-3.1.0.intellisense.js"; 
                public const string jquery_3_1_0_js = "~/Scripts/jquery-3.1.0.js"; 
                public const string jquery_3_1_0_min_js = "~/Scripts/jquery-3.1.0.min.js"; 
                public const string jquery_3_1_0_slim_js = "~/Scripts/jquery-3.1.0.slim.js"; 
                public const string jquery_3_1_0_slim_min_js = "~/Scripts/jquery-3.1.0.slim.min.js"; 
                public const string jquery_deparam_min_js = "~/Scripts/jquery-deparam.min.js"; 
                public const string jquery_ui_1_12_0_js = "~/Scripts/jquery-ui-1.12.0.js"; 
                public const string jquery_ui_1_12_0_min_js = "~/Scripts/jquery-ui-1.12.0.min.js"; 
                public const string jquery_ui_js = "~/Scripts/jquery-ui.js"; 
                public const string jquery_bxslider_js = "~/Scripts/jquery.bxslider.js"; 
                public const string jquery_bxslider_min_js = "~/Scripts/jquery.bxslider.min.js"; 
                public const string jquery_dataTables_min_js = "~/Scripts/jquery.dataTables.min.js"; 
                public const string jquery_easing_1_3_js = "~/Scripts/jquery.easing.1.3.js"; 
                public const string jquery_fitvids_js = "~/Scripts/jquery.fitvids.js"; 
                public const string jquery_metadata_js = "~/Scripts/jquery.metadata.js"; 
                public const string jquery_redirect_js = "~/Scripts/jquery.redirect.js"; 
                public const string jquery_tablesorter_js = "~/Scripts/jquery.tablesorter.js"; 
                public const string jquery_validate_date_js = "~/Scripts/jquery.validate.date.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string jssor_slider_min_js = "~/Scripts/jssor.slider.min.js"; 
                public const string jssor_slider_mini_js = "~/Scripts/jssor.slider.mini.js"; 
                public const string modernizr_2_8_3_js = "~/Scripts/modernizr-2.8.3.js"; 
                public const string placeholder_IE_fixes_js = "~/Scripts/placeholder-IE-fixes.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_matchmedia_addListener_js = "~/Scripts/respond.matchmedia.addListener.js"; 
                public const string respond_matchmedia_addListener_min_js = "~/Scripts/respond.matchmedia.addListener.min.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class assets_ 
            {
                public static partial class css 
                {
                    public static partial class footers 
                    {
                        public static class Assets
                        {
                            public const string footer_v1_css = "~/Content/assets/css/footers/footer-v1.css";
                        }
                    }
                    public static partial class headers 
                    {
                        public static class Assets
                        {
                            public const string header_default_css = "~/Content/assets/css/headers/header-default.css";
                        }
                    }
                    public static partial class plugins 
                    {
                        public static class Assets
                        {
                            public const string style_switcher_css = "~/Content/assets/css/plugins/style-switcher.css";
                        }
                    }
                    public static class Assets
                    {
                        public const string app_css = "~/Content/assets/css/app.css";
                        public const string blocks_css = "~/Content/assets/css/blocks.css";
                        public const string global_style_css = "~/Content/assets/css/global-style.css";
                        public const string ie8_css = "~/Content/assets/css/ie8.css";
                        public const string menudropdown_css = "~/Content/assets/css/menudropdown.css";
                        public const string plugins_css = "~/Content/assets/css/plugins.css";
                        public const string print_css = "~/Content/assets/css/print.css";
                        public const string style_css = "~/Content/assets/css/style.css";
                    }
                }
                public static partial class img 
                {
                    public static partial class bg 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class breadcrumbs 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class icons 
                    {
                        public static partial class flat 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static partial class social 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static partial class patterns 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class team 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class transparent 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static partial class plugins 
                {
                    public static partial class atomic 
                    {
                        public static class Assets
                        {
                            public const string atomic_css = "~/Content/assets/plugins/atomic/atomic.css";
                        }
                    }
                    public static partial class bootstrap 
                    {
                        public static partial class css 
                        {
                            public static class Assets
                            {
                                public const string bootstrap_rtl_min_css = "~/Content/assets/plugins/bootstrap/css/bootstrap-rtl.min.css";
                                public const string bootstrap_theme_css = "~/Content/assets/plugins/bootstrap/css/bootstrap-theme.css";
                                public const string bootstrap_theme_min_css = "~/Content/assets/plugins/bootstrap/css/bootstrap-theme.min.css";
                                public const string bootstrap_css = "~/Content/assets/plugins/bootstrap/css/bootstrap.css";
                                public const string bootstrap_min_css = "~/Content/assets/plugins/bootstrap/css/bootstrap.min.css";
                            }
                        }
                        public static partial class fonts 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static partial class js 
                        {
                            public static class Assets
                            {
                                public const string bootstrap_js = "~/Content/assets/plugins/bootstrap/js/bootstrap.js"; 
                                public const string bootstrap_min_js = "~/Content/assets/plugins/bootstrap/js/bootstrap.min.js"; 
                                public const string npm_js = "~/Content/assets/plugins/bootstrap/js/npm.js"; 
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static partial class Jssor 
                    {
                        public static class Assets
                        {
                            public const string jquery_bxslider_css = "~/Content/assets/plugins/Jssor/jquery.bxslider.css";
                            public const string jssor_slider_debug_js = "~/Content/assets/plugins/Jssor/jssor.slider.debug.js"; 
                        }
                    }
                    public static partial class line_icons 
                    {
                        public static partial class fonts 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                            public const string line_icons_css = "~/Content/assets/plugins/line-icons/line-icons.css";
                        }
                    }
                    public static partial class sky_forms_pro 
                    {
                        public static partial class skyforms 
                        {
                            public static partial class css 
                            {
                                public static class Assets
                                {
                                    public const string sky_forms_ie8_css = "~/Content/assets/plugins/sky-forms-pro/skyforms/css/sky-forms-ie8.css";
                                    public const string sky_forms_css = "~/Content/assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css";
                                }
                            }
                            public static partial class custom 
                            {
                                public static class Assets
                                {
                                    public const string custom_sky_forms_css = "~/Content/assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css";
                                }
                            }
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                        public const string animate_css = "~/Content/assets/plugins/animate.css";
                        public const string back_to_top_js = "~/Content/assets/plugins/back-to-top.js"; 
                        public const string smoothScroll_js = "~/Content/assets/plugins/smoothScroll.js"; 
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class Custom 
            {
                public static class Assets
                {
                    public const string app_css = "~/Content/Custom/app.css";
                    public const string vendor_css = "~/Content/Custom/vendor.css";
                }
            }
            public static partial class Documents 
            {
                public static class Assets
                {
                }
            }
            public static partial class font_awesome 
            {
                public static partial class css 
                {
                    public static class Assets
                    {
                        public const string font_awesome_animation_css = "~/Content/font-awesome/css/font-awesome-animation.css";
                        public const string font_awesome_css = "~/Content/font-awesome/css/font-awesome.css";
                        public const string font_awesome_min_css = "~/Content/font-awesome/css/font-awesome.min.css";
                    }
                }
                public static partial class fonts 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class less 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class scss 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class Fonts 
            {
                public static class Assets
                {
                }
            }
            public static partial class HelpFiles 
            {
                public static class Assets
                {
                }
            }
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static partial class Imports 
            {
                public static partial class Proposals 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class jsTree 
            {
                public static partial class images 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class themes 
                {
                    public static partial class bootstrap_theme 
                    {
                        public static class Assets
                        {
                            public const string style_css = "~/Content/jsTree/themes/bootstrap-theme/style.css";
                            public const string style_min_css = "~/Content/jsTree/themes/bootstrap-theme/style.min.css";
                        }
                    }
                    public static partial class @default 
                    {
                        public static class Assets
                        {
                            public const string style_css = "~/Content/jsTree/themes/default/style.css";
                            public const string style_min_css = "~/Content/jsTree/themes/default/style.min.css";
                        }
                    }
                    public static partial class default_dark 
                    {
                        public static class Assets
                        {
                            public const string style_css = "~/Content/jsTree/themes/default-dark/style.css";
                            public const string style_min_css = "~/Content/jsTree/themes/default-dark/style.min.css";
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                    public const string docs_css = "~/Content/jsTree/docs.css";
                }
            }
            public static partial class Logos 
            {
                public static class Assets
                {
                }
            }
            public static partial class pdfs 
            {
                public static class Assets
                {
                }
            }
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                        public const string jquery_ui_1_10_0_custom_css = "~/Content/themes/base/jquery-ui-1.10.0.custom.css";
                        public const string jquery_ui_1_9_2_custom_css = "~/Content/themes/base/jquery-ui-1.9.2.custom.css";
                        public const string jquery_ui_css = "~/Content/themes/base/jquery-ui.css";
                        public const string jquery_ui_min_css = "~/Content/themes/base/jquery-ui.min.css";
                        public const string jquery_ui_1_10_0_ie_css = "~/Content/themes/base/jquery.ui.1.10.0.ie.css";
                        public const string jquery_ui_1_9_2_ie_css = "~/Content/themes/base/jquery.ui.1.9.2.ie.css";
                        public const string selectable_css = "~/Content/themes/base/selectable.css";
                        public const string selectmenu_css = "~/Content/themes/base/selectmenu.css";
                        public const string slider_css = "~/Content/themes/base/slider.css";
                        public const string sortable_css = "~/Content/themes/base/sortable.css";
                        public const string spinner_css = "~/Content/themes/base/spinner.css";
                        public const string tabs_css = "~/Content/themes/base/tabs.css";
                        public const string theme_css = "~/Content/themes/base/theme.css";
                        public const string tooltip_css = "~/Content/themes/base/tooltip.css";
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_dialog_css = "~/Content/bootstrap-dialog.css";
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string buttons_dataTables_min_css = "~/Content/buttons.dataTables.min.css";
                public const string dataTables_bootstrap4_min_css = "~/Content/dataTables.bootstrap4.min.css";
                public const string fonts_css = "~/Content/fonts.css";
                public const string jqGrid_bootstrap_css = "~/Content/jqGrid.bootstrap.css";
                public const string jquery_dataTables_min_css = "~/Content/jquery.dataTables.min.css";
                public const string PagedList_css = "~/Content/PagedList.css";
                public const string reports_css = "~/Content/reports.css";
                public const string Site_css = "~/Content/Site.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


